# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coral Celeste Frazer
email: coralcelestefrazer@gmail.com
description: "Coral Celeste Frazer is a writer of nonfiction for teens. She has master’s degree in sociology from Princeton University and a long-standing interest in issues of inequality, collective action, and social justice. Her first book, Economic Inequality: The American Dream Under Siege, garnered starred reviews from Booklist and Kirkus Reviews and was chosen as one of the best books of the year by the Bank Street College of Education. She also writes fiction for adults and teens. She has lived in Colorado, Oregon, New Jersey, and Boston, and now resides in Norwich, England with her husband and son."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.coralcelestefrazer.com/" # the base hostname & protocol for your site, e.g. http://example.com
gtm: true

permalink: /:categories/:title

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
